export const APP_NAME = '老王打印机'

export const COPY = {
  homeTitle: '激光雕刻',
  homeLead: '像用打印机一样，把图案刻到材料上',
  dropTitleDisconnected: '请先连接雕刻机',
  dropHintDisconnected: '插入 USB 后会自动查找',
  dropTitleConnected: '拖入图片开始雕刻',
  dropHintConnected: '图案导入会在后续版本提供',
  deviceDisconnected: '未检测到雕刻机',
  deviceDetecting: '正在查找雕刻机…',
  deviceConnected: '雕刻机已连接',
  deviceUnplugged: '雕刻机连接已断开',
  myMachine: '我的雕刻机',
  connectDevice: '连接设备',
  retryDetect: '重新检测',
  retry: '重试',
  connectHelp: '连接帮助',
  help: '帮助',
  settings: '设置',
  helpBody: '用雕刻机附带的数据线接到电脑。如果开着别的雕刻软件，请先退出。',
  settingsBody: '高级设置会在后续版本提供。现在不用填写端口或波特率。',
  importLater: '图案导入会在后续版本提供。',
  sizeSetupTitle: '设置工作区域',
  sizeSetupLead: '量一下台面能刻的宽和高，填好后就可以开始了。',
  sizeWidth: '宽',
  sizeHeight: '高',
  sizeUnit: '毫米',
  sizeDone: '完成',
  sizeInvalid: '请填写有效的宽和高。',
} as const
